// <auto-generated />
using System;
using EsApp.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EsApp.Persistence.Infrastructure.EsApp.Persistence.Migrations
{
    [DbContext(typeof(EsAppDbContext))]
    partial class EsAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EsApp.Persistence.Entity.UsersMasterEntity", b =>
                {
                    b.Property<Guid>("UsersMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("usersMasterId");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lastName");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationDate");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role");

                    b.Property<string>("StateRecord")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("stateRecord");

                    b.Property<string>("UserRegistration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("userRegistration");

                    b.HasKey("UsersMasterId");

                    b.ToTable("usersMaster", (string)null);

                    b.HasData(
                        new
                        {
                            UsersMasterId = new Guid("0c7c13f1-05cd-4d5a-9ad1-8d2b8f2e1b51"),
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Usuario",
                            LastName = "Caja",
                            Password = "123abc",
                            Role = "CAJA",
                            StateRecord = "A",
                            UserRegistration = "caja"
                        },
                        new
                        {
                            UsersMasterId = new Guid("9c4932e4-1c6d-4b5f-8d7e-7f0c4b13a9b2"),
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Usuario",
                            LastName = "Plataforma",
                            Password = "123abc",
                            Role = "PLATAFORMA",
                            StateRecord = "A",
                            UserRegistration = "plataforma"
                        },
                        new
                        {
                            UsersMasterId = new Guid("a7d3a1f4-0b2c-4f91-8a86-4db5e7c7d4e6"),
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Usuario",
                            LastName = "Gerente",
                            Password = "123abc",
                            Role = "GERENTE",
                            StateRecord = "A",
                            UserRegistration = "gerente"
                        });
                });

            modelBuilder.Entity("EsApp.Persistence.Entity.UsersSessionsMasterEntity", b =>
                {
                    b.Property<Guid>("UsersSessionsMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("usersSessionsMasterId");

                    b.Property<int>("AmountToken")
                        .HasColumnType("integer")
                        .HasColumnName("amountToken");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateExpiration");

                    b.Property<DateTime>("DateGenerate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateGenerate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationDate");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refreshToken");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<Guid>("UsersMasterId")
                        .HasColumnType("uuid")
                        .HasColumnName("usersMasterId");

                    b.HasKey("UsersSessionsMasterId");

                    b.HasIndex("UsersMasterId");

                    b.ToTable("usersSessionsMaster", (string)null);
                });

            modelBuilder.Entity("EsApp.Persistence.Entity.UsersSessionsMasterEntity", b =>
                {
                    b.HasOne("EsApp.Persistence.Entity.UsersMasterEntity", "UsersMaster")
                        .WithMany("Sessions")
                        .HasForeignKey("UsersMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsersMaster");
                });

            modelBuilder.Entity("EsApp.Persistence.Entity.UsersMasterEntity", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
