// <auto-generated />
using System;
using EsApp.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EsApp.Persistence.Infrastructure.EsApp.Persistence.Migrations
{
    [DbContext(typeof(EsAppDbContext))]
    [Migration("20260111221723_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EsApp.Persistence.Entity.CurrencyEntity", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("currencyId");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("currency");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationDate");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("shortName");

                    b.Property<string>("StateRecord")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasDefaultValue("A")
                        .HasColumnName("stateRecord");

                    b.HasKey("CurrencyId");

                    b.ToTable("currency", (string)null);

                    b.HasData(
                        new
                        {
                            CurrencyId = new Guid("d29fba7e-1a2b-4fe7-8c2f-813a4e5ec5a0"),
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "Bolivianos",
                            ShortName = "BOB",
                            StateRecord = "A"
                        },
                        new
                        {
                            CurrencyId = new Guid("5d8f6a1d-9c2a-4b2f-9d2c-3189d9a21c4b"),
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "Dolares",
                            ShortName = "USD",
                            StateRecord = "A"
                        });
                });

            modelBuilder.Entity("EsApp.Persistence.Entity.CustomersEntity", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("customerId");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("documentNumber");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lastName");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationDate");

                    b.Property<string>("StateRecord")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasDefaultValue("A")
                        .HasColumnName("stateRecord");

                    b.HasKey("CustomerId");

                    b.ToTable("customers", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("81b7d3a3-9e4b-4f5c-9d64-3d1d8f9b1a6c"),
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DocumentNumber = "12345678",
                            FirstName = "Carlos",
                            LastName = "Lopez",
                            StateRecord = "A"
                        },
                        new
                        {
                            CustomerId = new Guid("f3dbb0f0-9c42-4fa1-8e4d-1437254a9d0f"),
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DocumentNumber = "87654321",
                            FirstName = "Maria",
                            LastName = "Fernandez",
                            StateRecord = "A"
                        });
                });

            modelBuilder.Entity("EsApp.Persistence.Entity.PaymentsServicesEntity", b =>
                {
                    b.Property<Guid>("PaymentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("paymentsId");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customerId");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationDate");

                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("serviceProviderId");

                    b.Property<string>("StateRecord")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasDefaultValue("A")
                        .HasColumnName("stateRecord");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("status");

                    b.Property<Guid>("UsersMasterId")
                        .HasColumnType("uuid")
                        .HasColumnName("usersMasterId");

                    b.HasKey("PaymentsId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceProviderId");

                    b.HasIndex("UsersMasterId");

                    b.ToTable("paymentsServices", (string)null);
                });

            modelBuilder.Entity("EsApp.Persistence.Entity.ServiceProviderEntity", b =>
                {
                    b.Property<Guid>("ServiceProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("serviceProviderId");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currencyId");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationDate");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("service");

                    b.Property<string>("StateRecord")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasDefaultValue("A")
                        .HasColumnName("stateRecord");

                    b.HasKey("ServiceProviderId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("serviceProvider", (string)null);

                    b.HasData(
                        new
                        {
                            ServiceProviderId = new Guid("b6b2d52c-1b8f-4ec8-9b38-0de5f5cc6e92"),
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrencyId = new Guid("d29fba7e-1a2b-4fe7-8c2f-813a4e5ec5a0"),
                            Service = "Agua",
                            StateRecord = "A"
                        },
                        new
                        {
                            ServiceProviderId = new Guid("6e3dce1a-148a-4bf8-9b08-4b4a1e4cbe5a"),
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrencyId = new Guid("d29fba7e-1a2b-4fe7-8c2f-813a4e5ec5a0"),
                            Service = "Electricidad",
                            StateRecord = "A"
                        },
                        new
                        {
                            ServiceProviderId = new Guid("10c5e8f7-7c58-4d8e-9c4d-8c4d5d7a9d1f"),
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrencyId = new Guid("d29fba7e-1a2b-4fe7-8c2f-813a4e5ec5a0"),
                            Service = "Telecomunicaciones",
                            StateRecord = "A"
                        },
                        new
                        {
                            ServiceProviderId = new Guid("f7f18c0a-2f04-4c8f-9d17-9f0f8c3e7e2a"),
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrencyId = new Guid("5d8f6a1d-9c2a-4b2f-9d2c-3189d9a21c4b"),
                            Service = "Starlink",
                            StateRecord = "A"
                        });
                });

            modelBuilder.Entity("EsApp.Persistence.Entity.UsersMasterEntity", b =>
                {
                    b.Property<Guid>("UsersMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("usersMasterId");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lastName");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationDate");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role");

                    b.Property<string>("StateRecord")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasDefaultValue("A")
                        .HasColumnName("stateRecord");

                    b.Property<string>("UserRegistration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("userRegistration");

                    b.HasKey("UsersMasterId");

                    b.ToTable("usersMaster", (string)null);

                    b.HasData(
                        new
                        {
                            UsersMasterId = new Guid("0c7c13f1-05cd-4d5a-9ad1-8d2b8f2e1b51"),
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Usuario",
                            LastName = "Caja",
                            Password = "123abc",
                            Role = "CAJA",
                            StateRecord = "A",
                            UserRegistration = "caja"
                        },
                        new
                        {
                            UsersMasterId = new Guid("9c4932e4-1c6d-4b5f-8d7e-7f0c4b13a9b2"),
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Usuario",
                            LastName = "Plataforma",
                            Password = "123abc",
                            Role = "PLATAFORMA",
                            StateRecord = "A",
                            UserRegistration = "plataforma"
                        },
                        new
                        {
                            UsersMasterId = new Guid("a7d3a1f4-0b2c-4f91-8a86-4db5e7c7d4e6"),
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Usuario",
                            LastName = "Gerente",
                            Password = "123abc",
                            Role = "GERENTE",
                            StateRecord = "A",
                            UserRegistration = "gerente"
                        });
                });

            modelBuilder.Entity("EsApp.Persistence.Entity.UsersSessionsMasterEntity", b =>
                {
                    b.Property<Guid>("UsersSessionsMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("usersSessionsMasterId");

                    b.Property<int>("AmountToken")
                        .HasColumnType("integer")
                        .HasColumnName("amountToken");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateExpiration");

                    b.Property<DateTime>("DateGenerate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateGenerate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationDate");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refreshToken");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<Guid>("UsersMasterId")
                        .HasColumnType("uuid")
                        .HasColumnName("usersMasterId");

                    b.HasKey("UsersSessionsMasterId");

                    b.HasIndex("UsersMasterId");

                    b.ToTable("usersSessionsMaster", (string)null);
                });

            modelBuilder.Entity("EsApp.Persistence.Entity.PaymentsServicesEntity", b =>
                {
                    b.HasOne("EsApp.Persistence.Entity.CustomersEntity", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsApp.Persistence.Entity.ServiceProviderEntity", "ServiceProvider")
                        .WithMany("Payments")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsApp.Persistence.Entity.UsersMasterEntity", "UsersMaster")
                        .WithMany("Payments")
                        .HasForeignKey("UsersMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ServiceProvider");

                    b.Navigation("UsersMaster");
                });

            modelBuilder.Entity("EsApp.Persistence.Entity.ServiceProviderEntity", b =>
                {
                    b.HasOne("EsApp.Persistence.Entity.CurrencyEntity", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("EsApp.Persistence.Entity.UsersSessionsMasterEntity", b =>
                {
                    b.HasOne("EsApp.Persistence.Entity.UsersMasterEntity", "UsersMaster")
                        .WithMany("Sessions")
                        .HasForeignKey("UsersMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsersMaster");
                });

            modelBuilder.Entity("EsApp.Persistence.Entity.CustomersEntity", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("EsApp.Persistence.Entity.ServiceProviderEntity", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("EsApp.Persistence.Entity.UsersMasterEntity", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
